<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by generate_slds.py from web/src/assets/layerColors.json — do not hand-edit; edit that JSON and re-run the script instead. -->
<StyledLayerDescriptor version="1.0.0"
  xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd">
  <NamedLayer>
    <Name>eez</Name>
    <UserStyle>
      <Title>Exclusive Economic Zones</Title>
      <FeatureTypeStyle>
        <Rule>
          <PolygonSymbolizer>
            <Fill><CssParameter name="fill">#5fc9ff</CssParameter><CssParameter name="fill-opacity">0.05</CssParameter></Fill>
            <Stroke>
              <CssParameter name="stroke">#5fc9ff</CssParameter>
              <CssParameter name="stroke-width">1.1</CssParameter>
              <CssParameter name="stroke-dasharray">6 4</CssParameter>
            </Stroke>
          </PolygonSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
