# Regenerates the seven *_style.sld files below from
# web/src/assets/layerColors.json — the single canonical source for every
# color/width/opacity value that has to match between GeoServer's SLDs
# (consumed by non-OpenLayers WMS clients, e.g. QGIS or GeoServer's own
# layer preview) and the OpenLayers styling this app's own map actually
# renders (web/src/assets/contextLayers.ts, web/src/components/
# TacticalMap.tsx's polygonStyleFor/lineStyleFor). Before this script
# existed, both sides hand-duplicated these values independently with
# nothing keeping them in sync — already caught once, live: airfields'
# runway/taxiway stroke width had drifted (SLD: 0.5/0.3, the TS side: 0.4/
# 0.4) before both were pointed at the same JSON (this script reconciled
# that drift by keeping the TS side's values, since that's what the running
# app actually renders — SLD-only, no visible effect on the app itself).
#
# Not run automatically. Re-run after editing layerColors.json:
#
#   python3 generate_slds.py
#
# The *_style.sld files are still the ones checked in and uploaded by
# provision.sh — this script's only job is keeping their content in sync
# with layerColors.json; it doesn't change how they're provisioned.
#
# Only covers the layers layerColors.json actually has values for — ports,
# airfields, eez, shipping_lanes, submarine_cables, bathymetry_contours,
# drawn_shapes. live_point_style.sld, nais_style.sld and history_style.sld
# have no OpenLayers-side equivalent to drift from (the live tactical
# picture is rendered from the WebSocket feed, not WFS — see provision.sh's
# "Live Domain Tracks" comment) and are hand-maintained as before.
import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
COLORS_PATH = os.path.join(SCRIPT_DIR, '..', '..', 'web', 'src', 'assets', 'layerColors.json')

with open(COLORS_PATH) as f:
    C = json.load(f)

GENERATED_HEADER = (
    '<!-- GENERATED by generate_slds.py from web/src/assets/layerColors.json — '
    'do not hand-edit; edit that JSON and re-run the script instead. -->\n'
)

SLD_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
{header}<StyledLayerDescriptor version="1.0.0"
  xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd">
"""
SLD_FOOTER = "</StyledLayerDescriptor>\n"


def dasharray(values):
    return ' '.join(str(v) for v in values)


def point_style(layer_name, title, s):
    return SLD_HEADER.format(header=GENERATED_HEADER) + f"""  <NamedLayer>
    <Name>{layer_name}</Name>
    <UserStyle>
      <Title>{title}</Title>
      <FeatureTypeStyle>
        <Rule>
          <PointSymbolizer>
            <Graphic>
              <Mark>
                <WellKnownName>circle</WellKnownName>
                <Fill>
                  <CssParameter name="fill">{s['fill']}</CssParameter>
                  <CssParameter name="fill-opacity">{s['fillOpacity']}</CssParameter>
                </Fill>
                <Stroke>
                  <CssParameter name="stroke">{s['stroke']}</CssParameter>
                  <CssParameter name="stroke-width">{s['strokeWidth']}</CssParameter>
                </Stroke>
              </Mark>
              <Size>{s.get('size', 5)}</Size>
            </Graphic>
          </PointSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
""" + SLD_FOOTER


def polygon_style(layer_name, title, s):
    dash = f'\n              <CssParameter name="stroke-dasharray">{dasharray(s["strokeDasharray"])}</CssParameter>' if 'strokeDasharray' in s else ''
    return SLD_HEADER.format(header=GENERATED_HEADER) + f"""  <NamedLayer>
    <Name>{layer_name}</Name>
    <UserStyle>
      <Title>{title}</Title>
      <FeatureTypeStyle>
        <Rule>
          <PolygonSymbolizer>
            <Fill><CssParameter name="fill">{s['fill']}</CssParameter><CssParameter name="fill-opacity">{s['fillOpacity']}</CssParameter></Fill>
            <Stroke>
              <CssParameter name="stroke">{s['stroke']}</CssParameter>
              <CssParameter name="stroke-width">{s['strokeWidth']}</CssParameter>{dash}
            </Stroke>
          </PolygonSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
""" + SLD_FOOTER


def airfields_style():
    def rule(kind):
        s = C['airfields'][kind]
        return f"""        <Rule>
          <Name>{kind}</Name>
          <ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>kind</ogc:PropertyName><ogc:Literal>{kind}</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
          <PolygonSymbolizer>
            <Fill><CssParameter name="fill">{s['fill']}</CssParameter><CssParameter name="fill-opacity">{s['fillOpacity']}</CssParameter></Fill>
            <Stroke><CssParameter name="stroke">{s['stroke']}</CssParameter><CssParameter name="stroke-width">{s['strokeWidth']}</CssParameter></Stroke>
          </PolygonSymbolizer>
        </Rule>"""

    rules = '\n'.join(rule(k) for k in ('boundary', 'runway', 'taxiway'))
    return SLD_HEADER.format(header=GENERATED_HEADER) + f"""  <NamedLayer>
    <Name>airfields</Name>
    <UserStyle>
      <Title>Airfields</Title>
      <FeatureTypeStyle>
{rules}
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
""" + SLD_FOOTER


def line_rules_by_property(prop, keys, styles):
    def rule(key):
        s = styles[key]
        dash = f'<CssParameter name="stroke-dasharray">{dasharray(s["strokeDasharray"])}</CssParameter>' if 'strokeDasharray' in s else ''
        return f"""        <Rule>
          <Name>{key}</Name>
          <ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>{prop}</ogc:PropertyName><ogc:Literal>{key}</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
          <LineSymbolizer>
            <Stroke><CssParameter name="stroke">{s['stroke']}</CssParameter><CssParameter name="stroke-width">{s['strokeWidth']}</CssParameter><CssParameter name="stroke-opacity">{s['strokeOpacity']}</CssParameter>{dash}</Stroke>
          </LineSymbolizer>
        </Rule>"""

    return '\n'.join(rule(k) for k in keys)


def shipping_lanes_style():
    rules = line_rules_by_property('lane_type', ('major', 'middle', 'minor', 'chokepoint'), C['shippingLanes'])
    return SLD_HEADER.format(header=GENERATED_HEADER) + f"""  <NamedLayer>
    <Name>shipping_lanes</Name>
    <UserStyle>
      <Title>Shipping Lanes</Title>
      <FeatureTypeStyle>
{rules}
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
""" + SLD_FOOTER


def submarine_cables_style():
    rules = line_rules_by_property('status', ('operational', 'abandoned'), C['submarineCables'])
    return SLD_HEADER.format(header=GENERATED_HEADER) + f"""  <NamedLayer>
    <Name>submarine_cables</Name>
    <UserStyle>
      <Title>Submarine Cables</Title>
      <FeatureTypeStyle>
{rules}
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
""" + SLD_FOOTER


def bathymetry_style():
    shallow, mid, deep = C['bathymetry']['shallow'], C['bathymetry']['mid'], C['bathymetry']['deep']
    return SLD_HEADER.format(header=GENERATED_HEADER) + f"""  <NamedLayer>
    <Name>bathymetry_contours</Name>
    <UserStyle>
      <Title>Bathymetry Contours</Title>
      <FeatureTypeStyle>
        <Rule>
          <Name>shallow</Name>
          <ogc:Filter><ogc:PropertyIsLessThan><ogc:PropertyName>depth_m</ogc:PropertyName><ogc:Literal>200</ogc:Literal></ogc:PropertyIsLessThan></ogc:Filter>
          <LineSymbolizer>
            <Stroke><CssParameter name="stroke">{shallow['stroke']}</CssParameter><CssParameter name="stroke-width">{shallow['strokeWidth']}</CssParameter><CssParameter name="stroke-opacity">{shallow['strokeOpacity']}</CssParameter></Stroke>
          </LineSymbolizer>
        </Rule>
        <Rule>
          <Name>mid</Name>
          <ogc:Filter>
            <ogc:And>
              <ogc:PropertyIsGreaterThanOrEqualTo><ogc:PropertyName>depth_m</ogc:PropertyName><ogc:Literal>200</ogc:Literal></ogc:PropertyIsGreaterThanOrEqualTo>
              <ogc:PropertyIsLessThan><ogc:PropertyName>depth_m</ogc:PropertyName><ogc:Literal>1000</ogc:Literal></ogc:PropertyIsLessThan>
            </ogc:And>
          </ogc:Filter>
          <LineSymbolizer>
            <Stroke><CssParameter name="stroke">{mid['stroke']}</CssParameter><CssParameter name="stroke-width">{mid['strokeWidth']}</CssParameter><CssParameter name="stroke-opacity">{mid['strokeOpacity']}</CssParameter></Stroke>
          </LineSymbolizer>
        </Rule>
        <Rule>
          <Name>deep</Name>
          <ogc:Filter><ogc:PropertyIsGreaterThanOrEqualTo><ogc:PropertyName>depth_m</ogc:PropertyName><ogc:Literal>1000</ogc:Literal></ogc:PropertyIsGreaterThanOrEqualTo></ogc:Filter>
          <LineSymbolizer>
            <Stroke><CssParameter name="stroke">{deep['stroke']}</CssParameter><CssParameter name="stroke-width">{deep['strokeWidth']}</CssParameter><CssParameter name="stroke-opacity">{deep['strokeOpacity']}</CssParameter></Stroke>
          </LineSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
""" + SLD_FOOTER


FILES = {
    'ports_style.sld': point_style('ports', 'Maritime Ports', {**C['ports'], 'size': 5}),
    'airfields_style.sld': airfields_style(),
    'eez_style.sld': polygon_style('eez', 'Exclusive Economic Zones', C['eez']),
    'shipping_lanes_style.sld': shipping_lanes_style(),
    'submarine_cables_style.sld': submarine_cables_style(),
    'bathymetry_style.sld': bathymetry_style(),
    'drawn_shapes_style.sld': polygon_style('drawn_shapes', 'Drawn Shapes', C['drawnShapes']),
}

for filename, content in FILES.items():
    path = os.path.join(SCRIPT_DIR, filename)
    with open(path, 'w') as f:
        f.write(content)
    print(f'wrote {filename}')
